### ISSUE TITLE
/opt/vruby/share/ location an issue with stow?

### ISSUE THREAD

**Issue by joshgoebel** [joefiorini/vruby#12]
Isn't this location an issue if someone wants to run stow again to refresh the files or catch any changes that happen to vruby over time (new files added, etc)?  Running stow again would create a zillion symlinks to all the Ruby stuff in /usr/local/share, no?

What about `vruby-rubies` or something more isolated?

**Comment by joefiorini** [comment]
There's 2 uses of the `share` dir. `/usr/local/share/vruby` holds the `downloads.yml` while `/opt/vruby/share` has the installed rubies. I'm using `/usr/local` as the stow target, so it shouldn't conflict with `/opt/vruby`.
