### ISSUE TITLE
stow needs to be run with sudo?

### ISSUE THREAD

**Issue by joshgoebel** [joefiorini/vruby#13]
Should the README be updated?  `/usr/local` on my Mac is owned by root:admin, so the stow command fails.

**Comment by joshgoebel** [comment]
What about pushing this into vruby itself such as having a `/opt/vruby/bin/vruby stow`...?

**Comment by joefiorini** [comment]
I actually wan't a big fan of using stow. It was a little complex. I'd prefer to not support it long-term seeing as #1 is now closed (and I'd like to have actual packages for linux eventually).
