### ISSUE TITLE
top-level files probably should not be stowed

### ISSUE THREAD

**Issue by joshgoebel** [joefiorini/vruby#14]
- README.md
- ARCHITECTURE.md

Obviously if you believe in the use of stow you'd think it would be a good pattern for other packages to follow as well, so I'm thinking a package putting top-level files in the stow dir (/usr/local in the example here) would be a no-no... esp. common files like README that would be highly likely to overlap with other projects.

Not sure the quickest way to fix this... stow does have an --ignore.

**Comment by joefiorini** [comment]
Added a stow ignore.
