### ISSUE TITLE
Why is stow used for local vruby [target]?

### ISSUE THREAD

**Issue by joshgoebel** [joefiorini/vruby#17]
All it does (since there are no other stows present) is to symlink all the top-level dirs from `vruby/share/{version}`... wouldn't it be simpler to remove this dependency and just symlink the `vruby/share/{version}` itself?  What is `stow` adding here that I'm missing?

**Comment by joefiorini** [comment]
Originally I was doing a slightly more complicated symlink. You're probably right, at this point we could probably just use `ln -s` instead.

**Comment by joshgoebel** [comment]
Ok.  Along the same lines, what benefit does this additional level of indirection get us (a symlink to Ruby)?  Why not just set RUBY_ROOT to the actual location of the files?

**Comment by joefiorini** [comment]
Closing this thanks to #18
