### ISSUE TITLE
Basic OS X support

### ISSUE THREAD

**Issue by joefiorini** [joefiorini/vruby#2]
Support the same level that we already do on Linux. This means using a hard-coded URL for Traveling Ruby 2.2.0 OS X package. The basic rack example should work. To test:
1. Clone this repo
2. `brew install stow`
3. cd into `example` directory
4. Run `./0_start_here.sh` (and follow the instructions given afterwards)

You may see an error related to an rdoc generator. This does not affect usage at the moment (perhaps unless you need rdocs). You can safely ignore it, I will track it in a separate issue.
1. Run `bundle install`
2. Verify rack is installed to `.gem/ruby/2.2.0/gems/rack-1.6.0` (if there is no `.gem` directory, please reply here with the output of `gem environment`)
3. Run `./1_rack_app.sh`

This should load a simple rack app on port `8080`. If you can visit that URL and the above steps all passed, then all is well! If it works for you, I would appreciate a quick :+1: here just so I know it's working for others. Thanks!

**Comment by joefiorini** [comment]
@samdunne As of ef876970 I have implemented the above in the existing bash scripts. Would you mind giving it a try and reporting back the results? Thanks!

**Comment by samdunne** [comment]
No problem. Shall report back when I've tested it!

**Comment by samdunne** [comment]
`cp: failed to access ‘/opt/vruby/share/2.2.0’: Not a directory`

**Comment by joefiorini** [comment]
What had you run that gave you that error? Was it on `vruby install`?

**Comment by samdunne** [comment]
All I ran was `./0_start_here.sh`

**Comment by samdunne** [comment]
Ignore me. I did something stupid >.<

**Comment by samdunne** [comment]
Works :+1:

**Comment by joefiorini** [comment]
Great! I need to add a few more examples so we can see how it works with more advanced gems like rails and things with C extensions. Keeping this open until we can confirm a few more use cases.

**Comment by joefiorini** [comment]
Works fine with Rails. Closing this issue.
