### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by flips** [joefiorini/vruby#24]
Running on OSX 10.11.4, Homebrew 0.9.9, git rev. 2f20a.

Doing a **`brew install https://raw.githubusercontent.com/joefiorini/vruby/master/formula/vruby.rb`**
Result:

```
######################################################################## 100.0%
==> Downloading https://github.com/joefiorini/vruby/archive/master.zip
==> Downloading from https://codeload.github.com/joefiorini/vruby/zip/master
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: e91b28f50e3bfa8f94c56cc8c72c2c34c6219f4f23d3c41ee2f9011c3bfb7b01
Actual: 4eca51a2b7743000a3de3b58401b94f13143d45f5c52d0fc03ffc0bd11e7d03c
Archive: /Library/Caches/Homebrew/vruby-1.0-pre.zip
To retry an incomplete download, remove the file above.
```

**Comment by joefiorini** [comment]
Apparently that never really worked and trying to have a homebrew formula in the same repo as the code is a bad idea. I've moved the formula into a gist and recommend installing with `--HEAD` in the readme. I verified it works on my iMac. @flips Does this fix the problem for you?

**Comment by flips** [comment]
Yes, works now. Thanks 😄
