### ISSUE TITLE
Native Extension Support

### ISSUE THREAD

**Issue by joefiorini** [joefiorini/vruby#4]
> Traveling Ruby only supports a number of popular native extension gems, and only in some specific versions. You cannot use just any native extension gem.

Using Traveling Ruby may be a problem. I missed this when reading the docs the first time around. I know native extensions work great with Tokaido, I've run many Rails apps with it on my Mac. Unfortunately, I wasn't able to get Tokaido to build on my Linux machine (ran into problems with dependencies in SM). So we'll need another option. I want to stick with a pre-compiled Ruby; the install is practically instant.

**Comment by joefiorini** [comment]
I just pushed my test for installing & running nokogiri to the `gem-extensions` branch in this repo. If anyone has any ideas on this, I'd love to hear. Traveling Ruby is not really the right solution here, it was just a quick way to get started on this. Has anyone figured out building Tokaido on Linux (@mpapis)?

**Comment by mpapis** [comment]
use http://rvm.io/binaries/ - tokaido (the binary ruby version) is build exactly the same way as Linux version - with: `rvm install --movable` the main thing you have to switch to use different version manager when you switch plathorms

**Comment by joefiorini** [comment]
Thanks @mpapis. I saw these releases when I trying to build tokaido but wasn't sure if any of them worked on arch. I'm downloading them all now to see what works and what doesn't. If worse comes to worse I guess I let `rvm install --movable` download and compile a version then package it up for arch, right?

**Comment by joefiorini** [comment]
Looks like the latest Ubuntu build works great! Tried it with nokogiri & rmagick. Need to try a full Rails install before considering this issue closed.

**Comment by joefiorini** [comment]
I have now used vruby for a full Rails install, this is looking good.
